// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaHAPSA.Infrastructure.Persistence;

#nullable disable

namespace PruebaHAPSA.Infrastructure.Migrations
{
    [DbContext(typeof(PruebaHapsaDbContext))]
    [Migration("20260114203456_AddReservaVipInheritance")]
    partial class AddReservaVipInheritance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("PruebaHAPSA.Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoReserva")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservas");

                    b.HasDiscriminator<string>("TipoReserva").HasValue("Reserva");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PruebaHAPSA.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PruebaHAPSA.Domain.Entities.ReservaEstandar", b =>
                {
                    b.HasBaseType("PruebaHAPSA.Domain.Entities.Reserva");

                    b.HasDiscriminator().HasValue("Estandar");
                });

            modelBuilder.Entity("PruebaHAPSA.Domain.Entities.ReservaVip", b =>
                {
                    b.HasBaseType("PruebaHAPSA.Domain.Entities.Reserva");

                    b.Property<string>("CodigoVip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MesaPreferida")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Vip");
                });
#pragma warning restore 612, 618
        }
    }
}
